### ISSUE TITLE
Files relative to source file

### ISSUE THREAD

**Issue by chuyskywalker** [docpad/docpad-plugin-associatedfiles#10]
I've toyed about with the options a number of ways, but can't seem to get this to scan for file relative to the document being rendered. I would like this structure to work:

```
documents/
  subfolder/
    pictures.html.eco
    images/
      image1.jpg
      image2.jpg
```

So that I can keep my image files more closely related to the document they're about.

Is that possible now and I'm just missing it? Or is this a feature request?

Thanks!

**Comment by balupton** [comment]
Seems sensible. I'll be surprised if there wasn't a way to do this. I'm pretty queued up with stuff but perhaps try stack overflow with the docpad tag or our slack channel at slack.bevry.me and someone will be able to help

**Comment by balupton** [comment]
Try this in your config:

```
plugins:
    associatedfiles:
        associatedFilesPath: false
        useRelativeBase: true
```
